# Generated by Django 6.0.3 on 2026-03-11 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción Breve')),
                ('stock_actual', models.PositiveIntegerField(default=0, verbose_name='Stock Disponible')),
                ('umbral_amarillo', models.PositiveIntegerField(verbose_name='Aviso')),
                ('umbral_rojo', models.PositiveIntegerField(verbose_name='Crítico')),
                ('factura', models.FileField(blank=True, null=True, upload_to='facturas/%Y/%m/', verbose_name='Factura (Opcional)')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
