# Generated by Django 6.0.3 on 2026-04-28 10:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import inventario.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('plan_activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=255)),
                ('producto_id', models.IntegerField(blank=True, null=True)),
                ('tipo_accion', models.CharField(choices=[('AJUSTE_RAPIDO', 'Ajuste rápido (+/-)'), ('MODAL_EDITAR', 'Producto Editado'), ('CREACION', 'Producto Creado'), ('ELIMINACION', 'Producto Eliminado')], max_length=20)),
                ('cambio', models.IntegerField(default=0)),
                ('stock_resultante', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('stock_anterior', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_historial', to='inventario.empresa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Movimiento',
                'verbose_name_plural': 'Historial de Movimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/', validators=[inventario.models.validar_tamano_foto])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('referencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referencia/SKU')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción Breve')),
                ('stock_actual', models.PositiveIntegerField(default=0, verbose_name='Stock Disponible')),
                ('umbrales_amarillo', models.PositiveIntegerField(default=10, verbose_name='Aviso')),
                ('umbrales_rojo', models.PositiveIntegerField(default=5, verbose_name='Crítico')),
                ('factura', models.FileField(blank=True, null=True, upload_to='facturas/%Y/%m/', verbose_name='Factura (Opcional)')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('dueño', 'Dueño'), ('admin', 'Administrador'), ('empleado', 'Empleado')], default='empleado', max_length=20)),
                ('es_fundador', models.BooleanField(default=False)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='inventario.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'unique_together': {('usuario', 'empresa')},
            },
        ),
    ]
