# Generated by Django 6.0.3 on 2026-03-17 09:14

import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referencia/SKU'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', validators=[inventario.models.validar_tamano_foto]),
        ),
    ]
