# Generated by Django 6.0.3 on 2026-04-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cumpleaños',
            field=models.DateField(blank=True, null=True),
        ),
    ]
