# Generated by Django 6.0.3 on 2026-04-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cif',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CIF/NIF'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
