# Generated by Django 6.0.3 on 2026-05-04 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verde_stokka', models.CharField(default='#003D00', max_length=7)),
                ('verde_secundario', models.CharField(default='#1CA300', max_length=7)),
                ('rojo_alerta', models.CharField(default='#C10D00', max_length=7)),
                ('amarillo_alerta', models.CharField(default='#F5C907', max_length=7)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tema', to='inventario.empresa')),
            ],
        ),
    ]
