# Generated by Django 6.0.3 on 2026-04-20 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_referencia_alter_perfil_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=255)),
                ('producto_id', models.IntegerField(blank=True, null=True)),
                ('tipo_accion', models.CharField(choices=[('AJUSTE_RAPIDP', 'Ajuste rápido (+/-)'), ('MODAL_EDITAR', 'Edición en Modal'), ('CREACION', 'Porudcto Creado'), ('ELIMINACION', 'Producto Eliminado')], max_length=20)),
                ('cambiio', models.IntegerField(default=0)),
                ('stock_resultante', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Movimiento',
                'verbose_name_plural': 'Historial de Movimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
