# Generated by Django 6.0.3 on 2026-05-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_temaempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tipo_daltonismo',
            field=models.CharField(choices=[('normal', 'Visión Normal'), ('protanopia', 'Protanopía (Rojo débil)'), ('deuteranopia', 'Deuteranopía (Verde débil)'), ('tritanopia', 'Tritanopía (Azul débil)'), ('acromatopsia', 'Acromatopsia (Blanco y Negro)')], default='normal', max_length=20),
        ),
    ]
