# Generated by Django 6.0.3 on 2026-04-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_perfil_cumpleaños'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='cumpleaños',
            new_name='fecha_nacimiento',
        ),
    ]
