# Generated by Django 6.0.3 on 2026-06-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_copiaseguridad'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historialmovimiento',
            index=models.Index(fields=['empresa', '-fecha'], name='inventario__empresa_c5fb5e_idx'),
        ),
    ]
