# Generated by Django 6.0.3 on 2026-04-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_historialmovimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialmovimiento',
            old_name='cambiio',
            new_name='cambio',
        ),
        migrations.RenameField(
            model_name='historialmovimiento',
            old_name='Usuario',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='historialmovimiento',
            name='tipo_accion',
            field=models.CharField(choices=[('AJUSTE_RAPIDO', 'Ajuste rápido (+/-)'), ('MODAL_EDITAR', 'Edición en Modal'), ('CREACION', 'Producto Creado'), ('ELIMINACION', 'Producto Eliminado')], max_length=20),
        ),
    ]
