# Generated by Django 6.0.3 on 2026-05-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_perfil_tipo_daltonismo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='tipo_daltonismo',
        ),
    ]
