# Generated by Django 6.0.3 on 2026-05-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_perfil_tipo_daltonismo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='filtro_daltonismo',
            field=models.CharField(choices=[('normal', 'Normal'), ('protanopia', 'Protanopia'), ('deuteranopia', 'Deuteranopia'), ('tritanopia', 'Tritanopia'), ('acromatopsia', 'Acromatopsia'), ('alto_contraste', 'Alto contraste')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='iconos_ayuda_visibles',
            field=models.BooleanField(default=True),
        ),
    ]
