# Generated by Django 6.0.3 on 2026-04-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_cambiio_historialmovimiento_cambio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmovimiento',
            name='stock_anterior',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historialmovimiento',
            name='tipo_accion',
            field=models.CharField(choices=[('AJUSTE_RAPIDO', 'Ajuste rápido (+/-)'), ('MODAL_EDITAR', 'Producto Editado'), ('CREACION', 'Producto Creado'), ('ELIMINACION', 'Producto Eliminado')], max_length=20),
        ),
    ]
