# Generated by Django 6.0.3 on 2026-05-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_perfil_filtro_daltonismo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='filtro_daltonismo',
            new_name='daltonismo',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='iconos_ayuda_visibles',
            new_name='iconos_info',
        ),
    ]
