# Generated by Django 6.0.3 on 2026-05-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_rename_filtro_daltonismo_perfil_daltonismo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fecha_desactivacion_programada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='renovacion_automatica',
            field=models.BooleanField(default=True),
        ),
    ]
