# Generated by Django 6.0.3 on 2026-04-27 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_perfil_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmovimiento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_historial', to='inventario.empresa'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='inventario.empresa'),
        ),
    ]
