"""
Django settings for stokka_project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _ 
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3))uh@5n*y@bbfk4g-3tzbvbk1qz37jfu#t%&aufuofz08e&_^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #Nuestras Apps
    'inventario',

    #Librerias externas
    'crispy_forms',
    'crispy_bootstrap5',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'inventario.middleware.PlanActivoMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stokka_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'inventario.context_processors.empresa_activa',
            ],
        },
    },
]

WSGI_APPLICATION = 'stokka_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

LANGUAGES = [
    ('es', _('Español')),
    ('en', _('Inglés')),
]


TIME_ZONE = 'Europe/Madrid'

USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

#Archivos Estáticos (CSS, JS, Logo...)
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

#Archivos Media (para el apartado de facturas e imagenes por si la quieren subir o no)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

LOGIN_URL = 'login'          # A donde van si intentan entrar al index sin cuenta
LOGIN_REDIRECT_URL = 'index' # A donde van justo después de loguearse

# LOGOUT_REDIRECT_URL = 'login' # A dónde va el usuario tras cerrar sesión
# LOGOUT_ON_GET = True          # Permite cerrar sesión haciendo clic en el enlace
AUTH_USER_MODEL = 'inventario.Usuario'

# ── EMAIL SMTP ──────────────────────────────────────────────────────────────
EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = 'smtp.gmail.com'
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = config('EMAIL_HOST_USER',     default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL  = config('DEFAULT_FROM_EMAIL',  default=f'Stokka <{EMAIL_HOST_USER}>')

# Aviso en arranque si el email no está configurado
if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    import warnings
    warnings.warn(
        "\n\n⚠️  EMAIL NO CONFIGURADO — El registro de usuarios no funcionará.\n"
        "   Crea o edita el archivo .env en la raíz del proyecto con:\n\n"
        "   EMAIL_HOST_USER=tucuenta@gmail.com\n"
        "   EMAIL_HOST_PASSWORD=abcdefghijklmnop   ← App Password de Google (16 chars)\n"
        "   DEFAULT_FROM_EMAIL=Stokka <tucuenta@gmail.com>\n\n"
        "   Genera el App Password en: https://myaccount.google.com/apppasswords\n"
        "   (Requiere verificación en dos pasos activada en tu cuenta Google)\n",
        stacklevel=2
    )
